CREATE TABLE medidas(
    id BIGINT NOT NULL AUTO_INCREMENT,
    descricao CHARACTER VARYING(6) NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY(id)
);


INSERT INTO MEDIDAS(descricao) values('g');
INSERT INTO MEDIDAS(descricao) values('mg');