CREATE TABLE farmacias(
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome CHARACTER VARYING(127) NOT NULL,
    bio CHARACTER VARYING(2112) NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paciente_id BIGINT NOT NULL,

    FOREIGN KEY(paciente_id) references pacientes(id),
    PRIMARY KEY(id)
);