CREATE TABLE lembretes(
    id BIGINT NOT NULL AUTO_INCREMENT,
    conteudo CHARACTER VARYING NOT NULL,
    farmacia_id BIGINT NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(farmacia_id) references farmacias(id),
    PRIMARY KEY(ID)
);