CREATE TABLE IF NOT EXISTS gramaturas (
    id BIGINT NOT NULL AUTO_INCREMENT,
    principio_ativo CHARACTER VARYING,
    valor_gramatura DOUBLE PRECISION NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);