CREATE TABLE pacientes(
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome CHARACTER VARYING(60) NOT NULL,
    sobrenome CHARACTER VARYING,
    idade INTEGER NOT NULL,
    data_nascimento DATE NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_alteracao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY(id)
);